### ISSUE TITLE
Yeti Integration

### ISSUE THREAD

**Issue by wajihyassine** [google/osdfir-infrastructure#27]
### Name and Version

charts/osdfir-infrastructure

### What is the problem this feature will solve?

Add [Yeti](https://github.com/yeti-platform/yeti) integration into OSDFIR Infrastructure for open source threat intel monitoring 

FYI @tomchop 

### What is the feature you are proposing to solve the problem?

Specifically create a standalone Yeti Helm chart then integration it as a dependency that can be enabled through OSDFIR Infrastructure or used standalone.

**Comment by hur** [comment]
I've hacked together a very basic working yeti chart this weekend on my homelab cluster.

Still needs quite a bit of work but would be happy to contribute it here eventually.

**Comment by wajihyassine** [comment]
Hi @hur thank you for the contribution!

We also hacked something similar for Yeti recently (apologies issue wasn't updated  in time to reflect that): https://github.com/wajihyassine/osdfir-infrastructure/tree/yeti

We can still take a look at how you approached it to see any major differences. There may also be some follow up work that will come out of the initial chart and if so can let you know about it then.
